### ISSUE TITLE
feat: 상품 메인 화면 전체 상품 목록 조회 기능 구현 

### ISSUE THREAD

**Issue by jhpodl** [ym1085/springboot-shopping-mall#123]
## ✅ 티켓 목적

> 상품 목록 출력은 메인 페이지에 [20개의 상품 이미지(*), 상품명(*), 상품 상세 내용(*), 가격(*)] 노출

## 🚀 상세 작업 내용

- [x] 상품 카테고리, 상품 테이블에 데이터 삽입
- [x] 20개의 상품 이미지, 상품명, 상품 상세 내용, 가격 가져오기
  - [x] 이미지 가져오려면 관리자가 BO에서 상품 등록 시 상품 이미지는 PRODUCT_FILE에 데이터 있어야 JOIN 해서 가져올 수 있음 
- [x] todo

## ✏️ 참고 사항

- [[Google Spread Sheet] 요구사항 분석](https://docs.google.com/spreadsheets/d/1Wppy4RiBwldQL77RcXoLq9OkdGnVFCzIv5TQO75fZl8/edit#gid=0)

**Comment by ym1085** [comment]
우선 local에 mysql 설치해서 환경 구성 후 resources > db > ddl > create + insert 실행하시면 될 것 같습니다

**Comment by jhpodl** [comment]
> @jhpodl
> 
> 우선 local에 mysql 설치해서 환경 구성 후 resources > db > ddl > create + insert 실행하시면 될 것 같습니다.
> 
> 상품 테이블의 경우 데이터가 기존에 존재하지 않아 데이터 INSERT도 필요할 것 같아요.

> 넵 우선 1단계 INSERT까지 완료하였습니다.

**Comment by jhpodl** [comment]
23.11.30 : 20개의 상품 이미지, 상품명, 상품 상세 내용, 가격 가져오기 DTO, entity, JPA repostiory 코드 작성하였고 TEst 코드 작성 후 로컬 테스트 진행 중 입니다.

**Comment by jhpodl** [comment]
20개의 상품 이미지, 상품명, 상품 상세 내용, 가격 가져오기 중 상품 이미지를 제외하고 repository에서 가져오는 부분을 테스트 하였습니다. 상세 작업 내용 추가하였습니다. 컨트롤러 개발 후 request 테스트 진행하려고 합니다.

**Comment by ym1085** [comment]
### 01. 20개의 상품 이미지, 상품명, 상품 상세 내용, 가격 가져오기
 
 - URL
   - /api/v1/products
 - 방향
   - 사용자 요청:param x -> 유효성 검증(@Valid) -> 상품 데이터 조회 -> 상품 + 상품 카테고리 + 상품 이미지 Table 조회
   - 이미지 가져오려면 관리자가 BO에서 상품 등록 시 상품 이미지는 PRODUCT_FILE에 데이터 있어야 JOIN 해서 가져올 수 있음
